import fs from "fs-extra";
import path from "path";
import { resolveFolders, type FolderOptions } from "./folder-paths.js";

const GENERATED_MARKER = "# Generated by aiblueprint-cli from Markdown agents.";
const IGNORED_ENTRY_NAMES = new Set([".DS_Store", "node_modules"]);
const DEFAULT_CODEX_SUBAGENT_MODEL = "gpt-5.6-terra";

type CodexReasoningEffort = "medium" | "high";

interface CodexModelSettings {
  model: string;
  reasoningEffort: CodexReasoningEffort;
}

export interface CodexAgentsRenderOptions extends FolderOptions {
  overwrite?: boolean;
}

export interface RenderedCodexAgent {
  source: string;
  target: string;
  name: string;
}

export interface SkippedCodexAgent {
  source: string;
  reason: string;
}

export interface CodexAgentsRenderResult {
  sourceDir: string;
  targetDir: string;
  rendered: RenderedCodexAgent[];
  skipped: SkippedCodexAgent[];
}

interface MarkdownAgent {
  sourcePath: string;
  frontmatter: Record<string, string>;
  body: string;
}

function parseFrontmatterValue(rawValue: string): string {
  const value = rawValue.trim();
  if (
    (value.startsWith("\"") && value.endsWith("\"")) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function parseMarkdownAgent(sourcePath: string, content: string): MarkdownAgent | null {
  if (!content.startsWith("---\n")) return null;

  const end = content.indexOf("\n---", 4);
  if (end === -1) return null;

  const frontmatterText = content.slice(4, end);
  const bodyStart = content.indexOf("\n", end + 4);
  const body = bodyStart === -1 ? "" : content.slice(bodyStart + 1).trim();
  const frontmatter: Record<string, string> = {};
  const lines = frontmatterText.split("\n");

  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;

    const key = match[1];
    const rawValue = match[2];

    if (rawValue === ">-" || rawValue === ">") {
      const foldedLines: string[] = [];
      while (index + 1 < lines.length && /^\s+/.test(lines[index + 1])) {
        index++;
        foldedLines.push(lines[index].trim());
      }
      frontmatter[key] = foldedLines.join(" ");
      continue;
    }

    if (rawValue === "|-" || rawValue === "|") {
      const literalLines: string[] = [];
      while (index + 1 < lines.length && /^\s+/.test(lines[index + 1])) {
        index++;
        literalLines.push(lines[index].replace(/^\s{2}/, ""));
      }
      frontmatter[key] = literalLines.join("\n");
      continue;
    }

    frontmatter[key] = parseFrontmatterValue(rawValue);
  }

  return { sourcePath, frontmatter, body };
}

function normalizeCodexAgentName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");

  if (!normalized) return "agent";
  if (/^[0-9]/.test(normalized)) return `agent_${normalized}`;
  return normalized;
}

function resolveCodexModelSettings(model: string | undefined): CodexModelSettings {
  switch (model?.trim().toLowerCase()) {
    case "opus":
      return {
        model: DEFAULT_CODEX_SUBAGENT_MODEL,
        reasoningEffort: "high",
      };
    case "haiku":
    case "sonnet":
    case "inherit":
    case "":
    case undefined:
      return {
        model: DEFAULT_CODEX_SUBAGENT_MODEL,
        reasoningEffort: "medium",
      };
    default:
      return {
        model,
        reasoningEffort: "medium",
      };
  }
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlMultilineLiteral(value: string): string {
  if (value.includes("'''")) {
    return tomlString(value);
  }
  return `'''\n${value}\n'''`;
}

function buildDeveloperInstructions(agent: MarkdownAgent): string {
  const toolHints = agent.frontmatter.tools?.trim();
  const color = agent.frontmatter.color?.trim();
  const notes: string[] = [];

  if (toolHints) {
    notes.push(`Original tool hints from the Markdown agent: ${toolHints}.`);
  }
  if (color) {
    notes.push(`Original display color metadata: ${color}.`);
  }

  const prefix = [
    `Source Markdown agent: ${path.basename(agent.sourcePath)}.`,
    ...notes,
  ].join("\n");

  return `${prefix}\n\n${agent.body}`.trim();
}

function renderToml(agent: MarkdownAgent): { name: string; content: string } | null {
  const rawName = agent.frontmatter.name?.trim();
  const description = agent.frontmatter.description?.trim();

  if (!rawName || !description || !agent.body) {
    return null;
  }

  const name = normalizeCodexAgentName(rawName);
  const modelSettings = resolveCodexModelSettings(agent.frontmatter.model);
  const lines = [
    GENERATED_MARKER,
    `# Source: ${agent.sourcePath}`,
    `name = ${tomlString(name)}`,
    `description = ${tomlString(description)}`,
    `model = ${tomlString(modelSettings.model)}`,
    `model_reasoning_effort = ${tomlString(modelSettings.reasoningEffort)}`,
  ];

  lines.push(`developer_instructions = ${tomlMultilineLiteral(buildDeveloperInstructions(agent))}`);
  lines.push("");

  return {
    name,
    content: lines.join("\n"),
  };
}

async function canOverwriteTarget(targetPath: string, overwrite: boolean): Promise<boolean> {
  if (overwrite) return true;
  const existing = await fs.readFile(targetPath, "utf-8").catch(() => null);
  return existing?.startsWith(GENERATED_MARKER) ?? false;
}

async function ensureRealTargetDir(targetDir: string): Promise<void> {
  const stat = await fs.lstat(targetDir).catch(() => null);
  if (stat?.isSymbolicLink()) {
    await fs.remove(targetDir);
  }
  await fs.ensureDir(targetDir);
}

export async function renderCodexAgentsFromMarkdown(
  options: CodexAgentsRenderOptions = {},
): Promise<CodexAgentsRenderResult> {
  const folders = resolveFolders(options);
  const sourceDir = path.join(folders.agentsDir, "agents");
  const targetDir = path.join(folders.codexDir, "agents");
  const result: CodexAgentsRenderResult = {
    sourceDir,
    targetDir,
    rendered: [],
    skipped: [],
  };

  if (!(await fs.pathExists(sourceDir))) {
    return result;
  }

  await fs.ensureDir(folders.codexDir);
  await ensureRealTargetDir(targetDir);

  const entries = await fs.readdir(sourceDir, { withFileTypes: true });
  for (const entry of entries) {
    if (IGNORED_ENTRY_NAMES.has(entry.name)) continue;
    if (!entry.isFile() || path.extname(entry.name) !== ".md") continue;

    const sourcePath = path.join(sourceDir, entry.name);
    const parsed = parseMarkdownAgent(sourcePath, await fs.readFile(sourcePath, "utf-8"));
    if (!parsed) {
      result.skipped.push({ source: sourcePath, reason: "Missing YAML frontmatter" });
      continue;
    }

    const rendered = renderToml(parsed);
    if (!rendered) {
      result.skipped.push({
        source: sourcePath,
        reason: "Missing name, description, or instruction body",
      });
      continue;
    }

    const targetPath = path.join(targetDir, `${rendered.name}.toml`);
    if ((await fs.pathExists(targetPath)) && !(await canOverwriteTarget(targetPath, Boolean(options.overwrite)))) {
      result.skipped.push({
        source: sourcePath,
        reason: `Codex agent already exists at ${targetPath}`,
      });
      continue;
    }

    await fs.writeFile(targetPath, rendered.content, "utf-8");
    result.rendered.push({
      source: sourcePath,
      target: targetPath,
      name: rendered.name,
    });
  }

  return result;
}
